#!/usr/bin/env python3
"""Generate the checked-in Vitaly v6 canonical keycode vocabulary."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


VITALY_VERSION = "0.1.32"
VITALY_COMMIT = "7ba52b0cf121e411434adcebf111e54b0ee470eb"
_ENTRY = re.compile(r'^\s*m\.insert\(0x([0-9A-Fa-f]+), "([^"]+)"\);$')
_CUSTOM_RANGES = ((0x7E00, 0x7E1F), (0x7E40, 0x7E5F))


def parse_fullnames(source: str) -> dict[int, str]:
    entries: dict[int, str] = {}
    in_fullnames = False
    for line in source.splitlines():
        if line.startswith("pub static FULLNAMES:"):
            in_fullnames = True
            continue
        if not in_fullnames:
            continue
        if line == "    m":
            break
        match = _ENTRY.fullmatch(line)
        if match is None:
            continue
        code = int(match[1], 16)
        if code in entries:
            raise ValueError(f"duplicate Vitaly keycode 0x{code:04X}")
        entries[code] = match[2]
    if not in_fullnames or not entries:
        raise ValueError("Vitaly v6 code_to_name::FULLNAMES was not found")
    return entries


def is_custom(code: int) -> bool:
    return any(start <= code <= end for start, end in _CUSTOM_RANGES)


def render_module(entries: dict[int, str]) -> str:
    standard = {
        code: name for code, name in sorted(entries.items()) if not is_custom(code)
    }
    lines = [
        '"""Canonical keycodes emitted by pinned Vitaly protocol v6.',
        "",
        "Generated by scripts/generate_vitaly_v6_keycodes.py; do not edit.",
        f"Source: Vitaly {VITALY_VERSION}, commit {VITALY_COMMIT}.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f'VITALY_VERSION = "{VITALY_VERSION}"',
        f'VITALY_COMMIT = "{VITALY_COMMIT}"',
        "",
        "STANDARD_KEYCODE_NAMES_BY_CODE: dict[int, str] = {",
    ]
    lines.extend(
        f'    0x{code:04X}: "{name}",' for code, name in standard.items()
    )
    lines.extend(
        [
            "}",
            "STANDARD_ATOMIC_KEYCODES = frozenset(",
            "    STANDARD_KEYCODE_NAMES_BY_CODE.values()",
            ")",
            "BASIC_KEYCODES = frozenset(",
            "    name",
            "    for code, name in STANDARD_KEYCODE_NAMES_BY_CODE.items()",
            "    if code <= 0x00FF",
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "keyball_config"
        / "vitaly_v6_keycodes.py",
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    try:
        rendered = render_module(parse_fullnames(arguments.source.read_text()))
    except (OSError, ValueError) as error:
        parser.error(str(error))

    if arguments.check:
        try:
            current = arguments.output.read_text()
        except OSError as error:
            print(f"generated vocabulary check failed: {error}", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                f"generated vocabulary is stale: {arguments.output}",
                file=sys.stderr,
            )
            return 1
        return 0

    arguments.output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
